### ISSUE TITLE
Q sigma implementation

### ISSUE THREAD

**Issue by ashish-sasha** [Breakend/MultiStepBootstrappingInRL#1]
I am following along the Q sigma implementation that you implemented but it's not quite matching up with the diagram on 7.6. For example, you have the notion of "E" https://github.com/Breakend/MultiStepBootstrappingInRL/blob/0ae39cde4670887da3f139847da76a5d356ee921/q_sigma.py#L146 But there is no "E" in pseudo-code 
I was wondering was this implementation from a previous version?

![Screenshot 2019-12-26 at 11 13 28 PM](https://user-images.githubusercontent.com/16604090/71746532-27913f80-2e3b-11ea-81e2-0bebd593322d.png)

**Comment by Breakend** [comment]
Hi,

It's been a while since I looked at this, but I believe I used a much older version of the textbook when I implemented this. You can see the E here and I believe this matches what you see in the code: https://arxiv.org/pdf/1703.01327.pdf
